apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-applications
        image: a0jx9f3ehkvj8.jfrog.io/artifactory/web-applications/
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: jfrogcred
