apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: web-application
        image: devopsmurali.jfrog.io/web-application/web-app:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: jfrogcred 
