apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtbXJlZGR5NDI0IiwicGFzc3dvcmQiOiJEb2NrZXJAMTIzIiwiZW1haWwiOiJ0ZWNod29ybGR3aXRobXVyYWxpQGdtYWlsLmNvbSIsImF1dGgiOiJiVzF5WldSa2VUUXlORHBFYjJOclpYSkFNVEl6In19fQ==
kind: Secret
metadata:
  name: dockerhubcred
type: kubernetes.io/dockerconfigjson
